# Site settings
title: Sterna
description: 'Proyecto León Marino, ecosistema sobre cambio climatico con enfoque en cianobacteria' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sterna.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/leonLogo.png"
logo-icon: "assets/img/branding/leonLogo.png"
logo-icon-SEO: "assets/img/branding/leonLogo.png" # must be a non SVG file

# Site settings for repo sterna 
title: Sterna
email: pedro.s.d.p@hotmail.com
author: Pedro Scheeffer 
description: "Ecositema de datos y papers, sobre cianobacteria en Uruguay"
baseurl: "/sterna"
url: "https://github.com/Dannysdp/Sterna"

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "assets/img/branding/leonLogo.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Pedro Scheeffer # add your name
author-pic: PedroScheeffer.jpg
about-author: Estudiante ingenieria de sistema, interesado en ciencia de los datos.

# Contact links
email: pedro.s.d.p@hotmail.com # Add your Email address
phone: 091820902 # Add your Phone number
#website: https://amaynez.github.io # Add your website
linkedin: pedro-scheeffer-799b9614a # Add your Linkedin handle
github: Dannysdp # Add your Github handle
#twitter: '@MvmThe' # Add your Twitter handle
#bandcamp: armandomaynez # Add your Bandcamp username
#stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
# mailchimp: 

# Tracker
# analytics: 
# fbadmin: 

# Paginate
paginate: 4
paginate_path: 'page:num'
words_per_minute: 200

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: "home" # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]